
f_name: 'faceNet'
model_name: deeplabv3plus
model_path: #hfrs/checkpoints/hfrs_model_best.pth.tar
train: true
model_specs:
    encoder_name: efficientnet-b0
    in_channels: 3
    classes: 19
    upsampling: 4
batch_size: 32
data_specs:
    width: 512
    height: 512
    dtype:
    image_type: 32bit
    rescale: false
    rescale_minima: auto
    rescale_maxima: auto
    label_type: mask
    is_categorical: true
    mask_channels: 1
    val_holdout_frac:
    data_workers: 4
training_data_csv: train.csv
validation_data_csv: val.csv
training_augmentation:
    augmentations:
        HorizontalFlip:
            p: 0.5
        RandomScale:
            scale_limit: [-0.3,0.3]
        PadIfNeeded:
            min_height: 512
            min_width: 512
        CenterCrop:
            height: 512
            width: 512
        #ChannelShuffle:
        #RandomRotate90:
        #    p: 0.5
        # RandomCrop:
        #     height: 512
        #     width: 512
        #     p: 1.0
        # Normalize:
        #     mean:
        #         - 0.5
        #     std:
        #         - 0.125
        #     max_pixel_value: 255.0
        #     p: 1.0
    p: 1.0
    shuffle: true
validation_augmentation:
    augmentations:
        # Resize:
        #     height: 512
        #     width: 512
        #     p: 1.0
        # CenterCrop:
        #     height: 512
        #     width: 512
        #     p: 1.0
        # Normalize:
        #     mean:
        #         - 0.5
        #     std:
        #         - 0.125
        #     max_pixel_value: 255.0
        #     p: 1.0
    p: 1.0
training:
    epochs: 200
    lr: 5e-2
    loss:
        diceloss:
            mode: multiclass
            from_logits: True
        crossentropyloss:
    loss_weights:
        diceloss: 1.0
        crossentropyloss: 1.0
    